### ISSUE TITLE
raiseError() not raising error

### ISSUE THREAD

**Issue by willvdmerwe** [PHPFrame/PHPFrame#8] opened 2010-04-14 11:36 UTC
the raiseError() method does not deliver expected results

my guess (shot in the dark) is that the error is never shown because the view designated to display it is never rendered (program flow stops at error?). i deduce this from seeing a shedload of 'ERROR: blah..blah' messages when it eventually got as far as rendering the view i was telling it to render.

**Comment by lupomontero** [comment] 2010-04-14 12:27
Hi Will,

I was having a similar problem with system events nor being displayed at all. The last commit in the master branch fixes the problem I was experiencing, but I'm not sure if it is the same problem you are having.

Can you install the last successful build [PHPFrame-0.0.24-build.102.tgz](http://dist.phpframe.org/PHPFrame-0.0.24-build.102.tgz) and see if the problem is fixed?

L

**Comment by lupomontero** [comment] 2010-07-08 21:21
This issue seems to have been fixed, so closing it for now.

**Closed as completed by lupomontero** 2010-07-08 21:21 UTC
